### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by yosbelms** [yosbelms/getjs#1]
> This issue is after a @donato comment (https://github.com/ubolonton/js-csp/issues/82#issuecomment-215699098)

Should be great to compare the performance of Aryn and js-csp, comparing _channels performance_ perhaps. If you think an other metric should be taked into account, discussion is open.

**Comment by donato** [comment]
I hope this may be helpful as a framework for testing throughput.
https://gist.github.com/donato/70ee94709d828721a8a562db16156ee2

**Comment by yosbelms** [comment]
@donato, thanks for your input i'll take your gist as inspiration.

**Comment by yosbelms** [comment]
@donato I'm getting some problems when testing js-csp and Aryn in the same script, seems js-csp hijacks the thread and doesn't let Aryn or any other scheduled code to execute until itself (js-csp) has completed all channel operations. It happens because js-csp has its own custom scheduler. Both libraries are based in generators, also called _collaborative threads_ but js-csp shows no collaboration with third party libs.

I'll make it in separated files.

**Comment by yosbelms** [comment]
I see now, what happen is js-csp uses `setImmediate`, Aryn uses `setTimeout`. node.js executes `setImmediate` timers before `setTimeout` timers. https://nodejs.org/api/timers.html#timers_setimmediate_callback_arg

Editted

**Comment by donato** [comment]
That's odd!

I would suggest doing the test of each library alone, perhaps on jsperf. I
can help set it up if you'd like.

**Comment by yosbelms** [comment]
I already have a setup to run it using node `child processes`, give me some time to finish. I will upload it in a separated repo.

**Comment by yosbelms** [comment]
**Insight**

1- Aryn is slower because is respectful with thirth party libraries and/or strategies, in the other hand JS-CSP is very fast at the cost of appropriating the thread to execute own channels operations.
2- Unbuffered channels (synchronous) are supposed to be slower than buffered channels (asynchronous), because the sync-async nature, but in JS-CSP behaves in a different way.

**Result**(in collaboration factor, greater is best):
Hardware: i5 3.10 Ghz 4GB RAM
-The results may vary depending on the garbage collector- 

JS-CSP unbuffered channel: 59
JS-CSP buffered channel: 5776
JS-CSP collaboration: 2

Aryn unbuffered channel: 10486
Aryn buffered channel: 6616
Aryn collaboration: 987

You can find the source-code at: https://github.com/yosbelms/aryn/tree/benchmark_comparison
